services:
  - type: web
    name: square-inventory-service
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn square_inventory_service:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_USE_PROD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SQUARE_WEBHOOK_SIGNATURE_KEY
        sync: false
